// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpkxnvmugvnpgjetkicw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxwa3hudm11Z3ZucGdqZXRraWN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMDUxNTgsImV4cCI6MjA2OTU4MTE1OH0.ce8zOV-l2YV2G64KmpzFJvbHxjHnS2uD7Pv6oQ4g7P4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});